version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /database/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - vacationnetwork
  vacationApi:
    depends_on:
      - db
    image: openjdk:11
    container_name: "vacationApi"
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./target/vacation-0.0.1-SNAPSHOT.jar:/app.jar"
    command: ['java', '-jar', '/app.jar']
    networks:
      - vacationnetwork
networks:
  vacationnetwork:
